In [6]:
import numpy as np

# ndarray 만들기, shape

In [7]:
array1 = np.array([1,2,3])
array2 = np.array([[1,2,3],[4,5,6]])
array3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])

print(array1.shape, array2.shape, array3.shape)

(3,) (2, 3) (2, 2, 3)


In [4]:
print(array1.ndim,array2.ndim,array3.ndim)

1 2 3


# ndarray의 데이터 타입

In [13]:
print(array1.dtype)

int32


### *하나의 ndarray안에는 하나의 데이터 타입만 가능! , list안에 서로 다른 타입 있으면 다 큰걸로 변환!

In [12]:
list1 = [1, 2, 'test']
array2 = np.array(list1)
print(array2.dtype)

list2 = [1,2,3.0]
array3 = np.array(list2)
print(array3.dtype)

<U11
float64


### astype() 으로 데이터 타입 변경, float -> int에서 소수점 이하는 버림

In [16]:
array_int = np.array([1,2,3])
array_float = array_int.astype('float64')
print(array_int.dtype, array_float.dtype)

array_float=np.array([1.9,1.5,1.3])
array_int = array_float.astype('int32')
print(array_int)

int32 float64
[1 1 1]


# arange, zeros, ones

In [19]:
array = np.arange(0,10,2)
print(array)

[0 2 4 6 8]


In [20]:
array = np.zeros((3,2), dtype='int32')
print(array)
array = np.zeros((2,2), dtype='float64')
print(array)
array = np.zeros((2,2))
print(array)

[[0 0]
 [0 0]
 [0 0]]
[[0. 0.]
 [0. 0.]]
[[0. 0.]
 [0. 0.]]


# reshape()

In [22]:
array = np.arange(10)
array2 = array.reshape(2,5)
array3 = array.reshape(5,2)

print(array2)
print(array3)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [23]:
array1 = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[7,8,9]]])
array1 = array1.reshape(-1,1)
array2 = array2.reshape(-1,1)
print(array1)
print(array2)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


# indexing

In [26]:
array1 = np.arange(10)
value = array1[3]
print(value, type(value), value.dtype)

3 <class 'numpy.int32'> int32


In [27]:
print(array1[-1], array[-2])

9 8


In [30]:
array = np.array([[1,2,3],[4,5,6]])
print(array[0])
print(array[0,2])
print(array[0][2])

[1 2 3]
3
3


In [35]:
array = np.arange(10)
# print([0:5])는 불가
print(array[0:5])
print(array[[0,1,2,3,4]])
print(type(array[0:5]))

[0 1 2 3 4]
[0 1 2 3 4]
<class 'numpy.ndarray'>


In [47]:
array=np.array([[1,2,3],[4,5,6],[7,8,9]])

print(array[0:2,1:3],"\n") #slice + slice
print(array[0,1:3],"\n") # single + slice
print(array[[0,2],0:3],"\n") # fancy + slice
print(array[[0,2],1],"\n") #fancy + single
print(array[[0,2],[0,2]]) #fancy + fancy

[[2 3]
 [5 6]] 

[2 3] 

[[1 2 3]
 [7 8 9]] 

[2 8] 

[1 9]


In [59]:
array = np.arange(10)
print(array>5)
print(type(array>5))
print(array[array>5])
index_array = np.array([6,7,8,9])
print(array[index_array])

[False False False False False False  True  True  True  True]
<class 'numpy.ndarray'>
[6 7 8 9]
[6 7 8 9]


# 행렬의 정렬 = sort(), argsort()

In [51]:
array= np.array([3,1,9,5])
sort_array = np.sort(array)
print(array)
print(sort_array)

sort_array = array.sort()
print(array)
print(sort_array)

[3 1 9 5]
[1 3 5 9]
[1 3 5 9]
None


In [56]:
array=np.array([1,7,8,9,4,5,1,3,8,5,1,6])
array.sort()
print(array)
print(array[0:10:2])

list1 = [1,1,1,3,4,5,5,6,7,8,8,9]
print(list1[0:10:2])

print(array[ : :-1])

[1 1 1 3 4 5 5 6 7 8 8 9]
[1 1 4 5 7]
[1, 1, 4, 5, 7]
[9 8 8 7 6 5 5 4 3 1 1 1]


In [57]:
array = np.array([[8,12],[7,1]])
print(np.sort(array, axis=0))
print(np.sort(array, axis=1))

[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [58]:
array = np.array([3,1,9,5])
index = np.argsort(array)
print(index)

[1 0 3 2]


# 선형대수 연산 - 행렬 내적과 전치 행렬 구하기

In [60]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(np.dot(a,b))
print(np.transpose(a))

[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
